services:
  postgres:
    container_name: postgres-api
    image: ${POSTGRES_IMAGE}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    networks:
      - feak-net

volumes:
  db_postgres:

networks:
  feak-net:
    driver: bridge
