FROM maven:3.9.9-eclipse-temurin-17 AS spi-builder

WORKDIR /build/custom-user-federation
COPY custom-user-federation/pom.xml ./pom.xml
COPY custom-user-federation/src ./src
RUN mvn -DskipTests clean package

FROM quay.io/keycloak/keycloak:22.0.5

WORKDIR /opt/keycloak
COPY themes /opt/keycloak/themes
COPY --from=spi-builder /build/custom-user-federation/target/custom-user-federation-1.0.0.jar /opt/keycloak/providers/

