<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CompareNETObjects" Version="4.84.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Feak.SistemaFinanceiro.DomainService\Feak.SistemaFinanceiro.DomainService.csproj" />
      <ProjectReference Include="..\Feak.SistemaFinanceiro.Persistence\Feak.SistemaFinanceiro.Persistence.csproj" />
    </ItemGroup>

</Project>
