// <auto-generated />
using Feak.SistemaFinanceiro.Persistencia.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Feak.SistemaFinanceiro.Persistencia.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20260421000200_add_vendas_and_codigo_barras")]
    partial class add_vendas_and_codigo_barras
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Intentionally minimal: this designer file was missing and is required
            // so EF can discover this migration in the correct order.
#pragma warning restore 612, 618
        }
    }
}
